### ISSUE TITLE
Question about the P-MOSFET in the input of 12v power

### ISSUE THREAD

**Issue by cheng3100** [pms67/STM32F4-Reference-PCB#1]
Hi, I look the entire video on youtube and I'm very interesting to make one. But I have a question about the P-MOSFET in the input of 12v power, What is its function? It is not work as a switch nor a amplifier.   I see you explain that its function is "Reverse Voltage Protection ". But why? It should be conduct in both direction if the voltage of g is low(on). It really confuse me. Can you give me more details about this？

**Comment by AngryMosfet** [comment]
@cheng3100  Take a look at this video. This guy will explain it better than I can. https://www.youtube.com/watch?v=IrB-FPcv1Dc&ab_channel=Afrotechmods

**Comment by cheng3100** [comment]
But I still have a questions, about the direction of current. Almost all the book say that the current should flow from S to D for P-MOSFET and from D to S for N-MOSFET. But in the reverse protection circuite it is from D to S for the P-MOSFET. So can I say both direction for MOSFET is ok?

**Comment by cheng3100** [comment]
Or can I just exchange the d and s in the reverse protection circuit？
For example I have seen circuite like this 
![图片](https://user-images.githubusercontent.com/25582840/103617584-78190c80-4f69-11eb-84e5-ad82a5c1b4b2.png)
